name = "Snapping Eden Zeus"
prefix = "sez"
author = "Ampersand"
files = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ampersand_ca.paa",
    "meta.cpp"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip sez_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
