name = "Snapping Eden Zeus"
prefix = "sez"
mainprefix = "z"

[properties]
author = "Ampersand"
url = "https://github.com/ampersand38/snapping-eden-zeus"

[files]
include = [
    "AUTHORS.txt",
    "LICENSE",
    "logo_ampersand_ca.paa",
    "mod.cpp",
    "README.md"
]
exclude = [
    ".vscode",
    "*.sqfc",
]

# Launched with `hemtt launch`
[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "3499977893", # Advanced Developer Tools
    "1645973522", # Intercept Minimal Dev
    "1585582292", # Arma Debug Engine
]
parameters = [
    "-window",
]

# Launched with `hemtt launch fata`
[hemtt.launch.fata]
extends = "default"
workshop = [
    "583496184",  # CUP Terrains - Core
    "2116880715", # FATA Tunnels
]
